#COMPANYNAME_CNC_AR_LAB.ps1
#Adam Ausburn

#This script converts a spreadsheet (using the ImportExcel module)
#into a flatfile for Centene.

#Change execution policy if needed (not signed)
#Set-ExecutionPolicy bypass -Scope Process -Force

#Script uses the ImportExcel module that can be installed
#using the below line if needed.
#Install-Module ImportExcel

Import-Module ImportExcel

#Remove old files generated by this script
Remove-Item * -Include "*.txt" -Exclude *Lab*

#Naming conventions
#Centene naming convention:
#COMPANYNAME_CNC_AR_SERVICE_$date
#COMPANYNAME_CNC_AR_LAB_$date

#Wellcare naming convention:
#COMPANYNAME_ESD_AR_SERVICE_$date
#COMPANYNAME_ESD_AR_LAB_$date

#File name generation using above format
$date = Get-Date
$date = $date.ToString('yyyyMMdd')
#$file = "COMPANYNAME_CNC_AR_SERVICE_$date.txt","COMPANYNAME_ESD_AR_SERVICE_$date.txt"
#$file = "COMPANYNAME_CNC_AR_SERVICE_.txt"
$file = "COMPANYNAME_CNC_AR_SERVICE_$date.txt"

#Import the reference spreadsheet for conversion
$import = Import-Excel Service_SDS_Template.xlsx -EndRow 200 |ConvertTo-Csv -NoTypeInformation -Delimiter '|' | % {$_.Replace('"','')} | % {$_.Replace('||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||','')}

#Remove time from date fields if present
$import = $import -replace ' 12:00:00 AM',''

#Output files
Add-content $file -Value $import